### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mikeliturbe** [preemptive-FP7/Modbus-Matlab-Simulator#1]
What is the license for this library? There is no copyright information in the source file headers or the README, and there is no License file.

I plan to use the code in this repository, but I would like to make sure I do it properly and that it is compatible with other types of software we are working with, mainly for redistribution.

As a software library designed to work with different types of models, I would recommend to use a lax, permissive copyright license.

**Comment by preemptive-FP7** [comment]
Dear Mikel,

I had left this project a bit aside lately. Sorry for the late reply. The license file is now available on the github page.

Kind Regards
